### ISSUE TITLE
ZMQ Log Publisher for the Manager

### ISSUE THREAD

**Issue by umesh-timalsina** [oele-isis-vanderbilt/ChimeraPy#97]
It might be nice to extend the current config to allow the publishing of the logs using ws transport. This can be a publisher that just streams the Manager Logs. However, this can be extended to incorporate other aspects like subscribing to other worker logs etc... The

**Comment by umesh-timalsina** [comment]
This could mean adding a section in chimerapy config. Not sure if this is the place it should live but starting out there:

```yaml
    ...
    logging: # logging configuration for the manager for publishing logs via ws
      publisher_port: 8687
      publisher-root-topic: chimerapy_manager_logs
      transport-type: ws
   ...
```


https://github.com/oele-isis-vanderbilt/ChimeraPy/blob/62340f6ee3700ad12c3f7c3a857e6c82c243b0de/chimerapy/_logger.py#L56-L66
```py
def getLogger(name: str, publisher_port: int = None, *, pub_handler_root_topic: str = '', transport:str = 'ws') -> logging.Logger:

    # Get the logging
    logger = logging.getLogger(name)

    if publisher_port is not None:
        # Add a handler to publish the logs to ws
        handler = PUBHandler(f"{transport}://*:{publisher_port}")
        handler.root_topic = pub_handler_root_topic
        logger.addHandler(handler)
        handler.setLevel(logging.DEBUG)
        # Use the same formatter as the console
        handler.setFormatter(logger.handlers[0].formatter)

    # Ensure that the configuration is set
    debug_loggers = os.environ.get("CHIMERAPY_DEBUG_LOGGERS", "").split(os.pathsep)
    if name in debug_loggers:
        logger.setLevel(logging.DEBUG)

    return logger

```
